"""add author bio and widden user name

Revision ID: 67b0f4d411f0
Revises: c497a5cc269b
Create Date: 2026-06-30 18:09:05.066227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b0f4d411f0'
down_revision: Union[str, Sequence[str], None] = 'c497a5cc269b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('bio', sa.String(length=500), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('authors', 'bio')
    # ### end Alembic commands ###
