"""added hashed_password to users and authors

Revision ID: 8647970f57c4
Revises: 67b0f4d411f0
Create Date: 2026-06-30 21:44:16.335283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8647970f57c4'
down_revision: Union[str, Sequence[str], None] = '67b0f4d411f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.drop_column('authors', 'hashed_password')
    # ### end Alembic commands ###
