"""sync varchar lengths

Revision ID: c497a5cc269b
Revises: 
Create Date: 2026-06-29 21:29:58.249427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c497a5cc269b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'content',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.String(length=700),
               existing_nullable=False)
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('posts', 'content',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=600),
               existing_nullable=False)
    op.alter_column('posts', 'title',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('comments', 'content',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=600),
               existing_nullable=False)
    # ### end Alembic commands ###
